version: "3.9"
services:
  wonderworld:
    image: wonderworld:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12193:12193"
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d wonderworld" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=wonderworld