version: '3.9'

networks:
    dev:
        driver: bridge
services:
  wonderworld:
    image: alesban/wonderworldbackend
    container_name: wonderworldbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7280:80"
    depends_on:
      - "wonderworld-db"
    networks:
      - dev
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Server=wonderworld-db;Port=5432;Database=wonderworld;User Id=postgres;Password=postgres123;Integrated Security=true;Pooling=true;
        
  wonderworld-db:
    image: postgres
    container_name: wonderworld-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=wonderworld
    networks:
      - dev
    volumes:
      - wonderworld-data:/var/lib/postgresql/data
volumes:
  wonderworld-data: